# Generated by Django 5.2.12 on 2026-03-03 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_assignments"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Assignments",
            new_name="Assignment",
        ),
    ]
