# Generated by Django 5.2.12 on 2026-03-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0004_studyresource_assignment_resources"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="course",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="grading_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="course",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="course",
            name="meeting_days",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="course",
            name="meeting_time",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="course",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="course",
            name="office_hours",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="course",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="syllabus_file",
            field=models.FileField(blank=True, null=True, upload_to="syllabi/"),
        ),
        migrations.AddField(
            model_name="course",
            name="syllabus_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="course",
            name="term",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="course",
            name="zoom_link",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("slate", "Slate"),
                    ("blue", "Blue"),
                    ("green", "Green"),
                    ("amber", "Amber"),
                    ("rose", "Rose"),
                    ("teal", "Teal"),
                ],
                default="slate",
                max_length=20,
            ),
        ),
    ]
